### ISSUE TITLE
Inconsistency on export

### ISSUE THREAD

**Issue by Stefaney-MP** [archi-contribs/database-plugin#125]
Sorry to bother you again, but version 2.2.21 now has a problem with exports. When i try to export a very basic model, i receive an inconsistency-error:

![image](https://user-images.githubusercontent.com/90898816/134287948-d1995afa-4dac-47a7-b0e8-69e2d025a041.png)

If i choose ignore, the model cannot be exported:

![image](https://user-images.githubusercontent.com/90898816/134288062-a355315d-1a32-49a6-bf87-1c185600df40.png)

Unfortunately this time the LOG doesn't give a clear indication what might be going wrong - at least not to me...

[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/7207939/DatabasePlugin.log)

Exporting the same model with 2.2.**19** works just fine, the exported version can even be imported by 2.2.21.

**Comment by herve91** [comment]
I'm aware of it, I experienced it myself yesterday. I'll send a fix today.

**Comment by herve91** [comment]
Fixed.

Please don't be surprised, I changed the numbering of my plugin's versions to stick to Archi's:
- 4.8.x versions will be compatible with Archi up to 4.8 (and not Archi 4.9)
- 4.9.x versions will be compatible with Archi up to 4.9

**Comment by Stefaney-MP** [comment]
I'm sorry to be a pain, but there are 2 issues remaining - one minor, one major:

- Minor: the download-file has an extension archiplugin**s**, which is not recognized by Archi - the extension should be .archiplugin to be recognized. 
- Major: export model, close model, import again, change something, try to export
![image](https://user-images.githubusercontent.com/90898816/134327209-ebf877af-9fe5-4198-8e25-3c0bbc4e245e.png)

**Comment by herve91** [comment]
The filename is fixed. I've been too quick to send it to GitHub. My mistake.

Regarding the illegalArgumentException, I need the end of the log file the log file in debug mode to investigate (at least the end of file, to know where the exception is raised).

My tests is similar to what you describe : import model, create new components + update others + delete some others, and then export back... and I did not experienced the error you describe.

**Comment by Stefaney-MP** [comment]
Sorry, i was planning on attaching the file but forgot.
I tested again, this time just import - change something - try to export
[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/7210190/DatabasePlugin.log)

**Comment by herve91** [comment]
Analyzing your log file, the error is raised because your model purpose is null (if not filled-in, it should be an empty string).

As a quick fix, you may write down a dot (or whatever char) in your model purpose and delete it right after. This will force the purpose string to be allocated.

To definitively fix this issue, I will do this replace operation in my export code. This way, the exception will never raise again.

I'll send the fix in the coming minutes ...

**Comment by Stefaney-MP** [comment]
Ok, i tried filling in something in the model purpose, then i did several import/export-operations - everything seems to work just fine!

Thanks again for your very quick answers and great support!

**Comment by herve91** [comment]
you're welcome :)

I close your issue.
